export const SET_PRODUCTS = 'SET_PRODUCTS'
export const SET_RESERVASMAP = 'SET_RESERVASMAP'
export const SET_EDIT_PRODUCTS_BTN = "SET_EDIT_PRODUCTS_BTN"
export const SET_EDIT_INPUT_VALUE = "SET_EDIT_INPUT_VALUE"
export const SET_USER = "SET_USER"
export const SET_CART = "SET_CART"
export const SET_CART_COUNTER = "SET_CART_COUNTER"